# Generated by Django 3.2.5 on 2021-08-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_send_pub_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='send',
            new_name='Message',
        ),
    ]
