# Generated by Django 3.2.5 on 2021-10-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmpuser',
            old_name='all_actions',
            new_name='city_activities',
        ),
        migrations.RenameField(
            model_name='tmpuser',
            old_name='now_actions',
            new_name='nature_activities',
        ),
        migrations.AddField(
            model_name='tmpuser',
            name='person_activities',
            field=models.TextField(null=True),
        ),
    ]
