# Generated by Django 3.2.5 on 2021-10-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='start',
            new_name='star',
        ),
    ]
