# Generated by Django 3.2.5 on 2021-08-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_text', models.CharField(max_length=200)),
                ('check_read', models.BooleanField(default=0)),
            ],
        ),
    ]
