# Generated by Django 3.2.5 on 2021-08-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
