# Generated by Django 3.2.5 on 2021-08-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_pub_data_message_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.BooleanField(default=1, null=True),
        ),
    ]
