# Generated by Django 3.2.5 on 2021-09-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_suvmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='suvmessage',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
