# Generated by Django 3.2.5 on 2021-09-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_suvmessage_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('all_actions', models.TextField(null=True)),
                ('now_actions', models.TextField(null=True)),
            ],
        ),
    ]
