# Generated by Django 3.2.5 on 2021-09-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
